# Generated by Django 5.0.6 on 2024-06-26 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(verbose_name='Cédula')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('apellido', models.TextField(verbose_name='Apellido')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('correo', models.TextField(verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.TextField(verbose_name='RUC')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('correo', models.TextField(verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrostore.categoria', verbose_name='Categoría')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrostore.marca', verbose_name='Marca')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrostore.proveedor', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.TextField(verbose_name='Nro. factura')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio_total', models.IntegerField(verbose_name='Precio total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrostore.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrostore.articulo', verbose_name='Artículo')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='electrostore.factura', verbose_name='Factura')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.TextField(verbose_name='Usuario')),
                ('password', models.TextField(verbose_name='Contraseña')),
                ('cedula', models.IntegerField(verbose_name='Cédula')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('apellido', models.TextField(verbose_name='Apellido')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('correo', models.TextField(unique=True, verbose_name='Correo')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrostore.roles', verbose_name='Rol')),
            ],
        ),
    ]
